//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelService.ValutaServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ValutaServiceReference.IValutaService")]
    public interface IValutaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/GetValutas", ReplyAction="http://tempuri.org/IValutaService/GetValutasResponse")]
        string[] GetValutas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/GetValutas", ReplyAction="http://tempuri.org/IValutaService/GetValutasResponse")]
        System.Threading.Tasks.Task<string[]> GetValutasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/GetConvertedValuta", ReplyAction="http://tempuri.org/IValutaService/GetConvertedValutaResponse")]
        double GetConvertedValuta(int inAmount, string outValuta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/GetConvertedValuta", ReplyAction="http://tempuri.org/IValutaService/GetConvertedValutaResponse")]
        System.Threading.Tasks.Task<double> GetConvertedValutaAsync(int inAmount, string outValuta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IValutaServiceChannel : HotelService.ValutaServiceReference.IValutaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValutaServiceClient : System.ServiceModel.ClientBase<HotelService.ValutaServiceReference.IValutaService>, HotelService.ValutaServiceReference.IValutaService {
        
        public ValutaServiceClient() {
        }
        
        public ValutaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValutaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValutaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValutaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetValutas() {
            return base.Channel.GetValutas();
        }
        
        public System.Threading.Tasks.Task<string[]> GetValutasAsync() {
            return base.Channel.GetValutasAsync();
        }
        
        public double GetConvertedValuta(int inAmount, string outValuta) {
            return base.Channel.GetConvertedValuta(inAmount, outValuta);
        }
        
        public System.Threading.Tasks.Task<double> GetConvertedValutaAsync(int inAmount, string outValuta) {
            return base.Channel.GetConvertedValutaAsync(inAmount, outValuta);
        }
    }
}
