#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
    using System.ComponentModel.DataAnnotations;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PROG6ASPNET")]
	public partial class DatabaseClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBoekingen(Boekingen instance);
    partial void UpdateBoekingen(Boekingen instance);
    partial void DeleteBoekingen(Boekingen instance);
    partial void InsertKlanten(Klanten instance);
    partial void UpdateKlanten(Klanten instance);
    partial void DeleteKlanten(Klanten instance);
    partial void InsertGebruiker(Gebruiker instance);
    partial void UpdateGebruiker(Gebruiker instance);
    partial void DeleteGebruiker(Gebruiker instance);
    partial void InsertHotelkamer(Hotelkamer instance);
    partial void UpdateHotelkamer(Hotelkamer instance);
    partial void DeleteHotelkamer(Hotelkamer instance);
    partial void InsertRollen(Rollen instance);
    partial void UpdateRollen(Rollen instance);
    partial void DeleteRollen(Rollen instance);
    #endregion
		
		public DatabaseClassesDataContext() : 
				base(global::DataAccessLayer.Properties.Settings.Default.PROG6ASPNETConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Boekingen> Boekingens
		{
			get
			{
				return this.GetTable<Boekingen>();
			}
		}
		
		public System.Data.Linq.Table<Klanten> Klantens
		{
			get
			{
				return this.GetTable<Klanten>();
			}
		}
		
		public System.Data.Linq.Table<Gebruiker> Gebruikers
		{
			get
			{
				return this.GetTable<Gebruiker>();
			}
		}
		
		public System.Data.Linq.Table<Hotelkamer> Hotelkamers
		{
			get
			{
				return this.GetTable<Hotelkamer>();
			}
		}
		
		public System.Data.Linq.Table<Rollen> Rollens
		{
			get
			{
				return this.GetTable<Rollen>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Boekingen")]
	public partial class Boekingen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _Startdatum;
		
		private System.DateTime _Einddatum;
		
		private System.Nullable<decimal> _Prijs;
		
		private string _FactuurAdres;
		
		private System.Nullable<long> _Bankrekening;
		
		private string _Status;
		
		private int _Boeking_KlantNr;
		
		private int _Boeking_KamerNr;
		
		private int _BoekingsNr;
		
		private EntityRef<Klanten> _Klanten;
		
		private EntityRef<Hotelkamer> _Hotelkamer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStartdatumChanging(System.DateTime value);
    partial void OnStartdatumChanged();
    partial void OnEinddatumChanging(System.DateTime value);
    partial void OnEinddatumChanged();
    partial void OnPrijsChanging(System.Nullable<decimal> value);
    partial void OnPrijsChanged();
    partial void OnFactuurAdresChanging(string value);
    partial void OnFactuurAdresChanged();
    partial void OnBankrekeningChanging(System.Nullable<long> value);
    partial void OnBankrekeningChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnBoeking_KlantNrChanging(int value);
    partial void OnBoeking_KlantNrChanged();
    partial void OnBoeking_KamerNrChanging(int value);
    partial void OnBoeking_KamerNrChanged();
    partial void OnBoekingsNrChanging(int value);
    partial void OnBoekingsNrChanged();
    #endregion
		
		public Boekingen()
		{
			this._Klanten = default(EntityRef<Klanten>);
			this._Hotelkamer = default(EntityRef<Hotelkamer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Startdatum", DbType="Date NOT NULL")]
		public System.DateTime Startdatum
		{
			get
			{
				return this._Startdatum;
			}
			set
			{
				if ((this._Startdatum != value))
				{
					this.OnStartdatumChanging(value);
					this.SendPropertyChanging();
					this._Startdatum = value;
					this.SendPropertyChanged("Startdatum");
					this.OnStartdatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Einddatum", DbType="Date NOT NULL")]
		public System.DateTime Einddatum
		{
			get
			{
				return this._Einddatum;
			}
			set
			{
				if ((this._Einddatum != value))
				{
					this.OnEinddatumChanging(value);
					this.SendPropertyChanging();
					this._Einddatum = value;
					this.SendPropertyChanged("Einddatum");
					this.OnEinddatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prijs", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Prijs
		{
			get
			{
				return this._Prijs;
			}
			set
			{
				if ((this._Prijs != value))
				{
					this.OnPrijsChanging(value);
					this.SendPropertyChanging();
					this._Prijs = value;
					this.SendPropertyChanged("Prijs");
					this.OnPrijsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FactuurAdres", DbType="NVarChar(50)")]
		public string FactuurAdres
		{
			get
			{
				return this._FactuurAdres;
			}
			set
			{
				if ((this._FactuurAdres != value))
				{
					this.OnFactuurAdresChanging(value);
					this.SendPropertyChanging();
					this._FactuurAdres = value;
					this.SendPropertyChanged("FactuurAdres");
					this.OnFactuurAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bankrekening", DbType="BigInt")]
		public System.Nullable<long> Bankrekening
		{
			get
			{
				return this._Bankrekening;
			}
			set
			{
				if ((this._Bankrekening != value))
				{
					this.OnBankrekeningChanging(value);
					this.SendPropertyChanging();
					this._Bankrekening = value;
					this.SendPropertyChanged("Bankrekening");
					this.OnBankrekeningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boeking_KlantNr", DbType="Int NOT NULL")]
		public int Boeking_KlantNr
		{
			get
			{
				return this._Boeking_KlantNr;
			}
			set
			{
				if ((this._Boeking_KlantNr != value))
				{
					if (this._Klanten.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBoeking_KlantNrChanging(value);
					this.SendPropertyChanging();
					this._Boeking_KlantNr = value;
					this.SendPropertyChanged("Boeking_KlantNr");
					this.OnBoeking_KlantNrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boeking_KamerNr", DbType="Int NOT NULL")]
		public int Boeking_KamerNr
		{
			get
			{
				return this._Boeking_KamerNr;
			}
			set
			{
				if ((this._Boeking_KamerNr != value))
				{
					if (this._Hotelkamer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBoeking_KamerNrChanging(value);
					this.SendPropertyChanging();
					this._Boeking_KamerNr = value;
					this.SendPropertyChanged("Boeking_KamerNr");
					this.OnBoeking_KamerNrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoekingsNr", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int BoekingsNr
		{
			get
			{
				return this._BoekingsNr;
			}
			set
			{
				if ((this._BoekingsNr != value))
				{
					this.OnBoekingsNrChanging(value);
					this.SendPropertyChanging();
					this._BoekingsNr = value;
					this.SendPropertyChanged("BoekingsNr");
					this.OnBoekingsNrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klanten_Boekingen", Storage="_Klanten", ThisKey="Boeking_KlantNr", OtherKey="KlantNummer", IsForeignKey=true)]
		public Klanten Klanten
		{
			get
			{
				return this._Klanten.Entity;
			}
			set
			{
				Klanten previousValue = this._Klanten.Entity;
				if (((previousValue != value) 
							|| (this._Klanten.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Klanten.Entity = null;
						previousValue.Boekingens.Remove(this);
					}
					this._Klanten.Entity = value;
					if ((value != null))
					{
						value.Boekingens.Add(this);
						this._Boeking_KlantNr = value.KlantNummer;
					}
					else
					{
						this._Boeking_KlantNr = default(int);
					}
					this.SendPropertyChanged("Klanten");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hotelkamer_Boekingen", Storage="_Hotelkamer", ThisKey="Boeking_KamerNr", OtherKey="KamerNummer", IsForeignKey=true)]
		public Hotelkamer Hotelkamer
		{
			get
			{
				return this._Hotelkamer.Entity;
			}
			set
			{
				Hotelkamer previousValue = this._Hotelkamer.Entity;
				if (((previousValue != value) 
							|| (this._Hotelkamer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hotelkamer.Entity = null;
						previousValue.Boekingens.Remove(this);
					}
					this._Hotelkamer.Entity = value;
					if ((value != null))
					{
						value.Boekingens.Add(this);
						this._Boeking_KamerNr = value.KamerNummer;
					}
					else
					{
						this._Boeking_KamerNr = default(int);
					}
					this.SendPropertyChanged("Hotelkamer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Klanten")]
	public partial class Klanten : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KlantNummer;
		
		private string _Voornaam;
		
		private string _Achternaam;
		
		private string _tussenvoegsel;
		
		private System.DateTime _Geboortedatum;
		
		private string _Geslacht;
		
		private string _Adres;
		
		private string _Postcode;
		
		private string _Woonplaats;
		
		private string _Email;
		
		private System.Nullable<int> _userID;
		
		private EntitySet<Boekingen> _Boekingens;
		
		private EntityRef<Gebruiker> _Gebruiker;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKlantNummerChanging(int value);
    partial void OnKlantNummerChanged();
    partial void OnVoornaamChanging(string value);
    partial void OnVoornaamChanged();
    partial void OnAchternaamChanging(string value);
    partial void OnAchternaamChanged();
    partial void OntussenvoegselChanging(string value);
    partial void OntussenvoegselChanged();
    partial void OnGeboortedatumChanging(System.DateTime value);
    partial void OnGeboortedatumChanged();
    partial void OnGeslachtChanging(string value);
    partial void OnGeslachtChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnPostcodeChanging(string value);
    partial void OnPostcodeChanged();
    partial void OnWoonplaatsChanging(string value);
    partial void OnWoonplaatsChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnuserIDChanging(System.Nullable<int> value);
    partial void OnuserIDChanged();
    #endregion
		
		public Klanten()
		{
			this._Boekingens = new EntitySet<Boekingen>(new Action<Boekingen>(this.attach_Boekingens), new Action<Boekingen>(this.detach_Boekingens));
			this._Gebruiker = default(EntityRef<Gebruiker>);
			OnCreated();
		}
		
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlantNummer", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KlantNummer
		{
			get
			{
				return this._KlantNummer;
			}
			set
			{
				if ((this._KlantNummer != value))
				{
					this.OnKlantNummerChanging(value);
					this.SendPropertyChanging();
					this._KlantNummer = value;
					this.SendPropertyChanged("KlantNummer");
					this.OnKlantNummerChanged();
				}
			}
		}
		
        [Required]
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voornaam", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Voornaam
		{
			get
			{
				return this._Voornaam;
			}
			set
			{
				if ((this._Voornaam != value))
				{
					this.OnVoornaamChanging(value);
					this.SendPropertyChanging();
					this._Voornaam = value;
					this.SendPropertyChanged("Voornaam");
					this.OnVoornaamChanged();
				}
			}
		}
		
        [Required]
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Achternaam", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Achternaam
		{
			get
			{
				return this._Achternaam;
			}
			set
			{
				if ((this._Achternaam != value))
				{
					this.OnAchternaamChanging(value);
					this.SendPropertyChanging();
					this._Achternaam = value;
					this.SendPropertyChanged("Achternaam");
					this.OnAchternaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tussenvoegsel", DbType="NVarChar(10)")]
		public string tussenvoegsel
		{
			get
			{
				return this._tussenvoegsel;
			}
			set
			{
				if ((this._tussenvoegsel != value))
				{
					this.OntussenvoegselChanging(value);
					this.SendPropertyChanging();
					this._tussenvoegsel = value;
					this.SendPropertyChanged("tussenvoegsel");
					this.OntussenvoegselChanged();
				}
			}
		}
		
        [Required]
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geboortedatum", DbType="Date NOT NULL")]
		public System.DateTime Geboortedatum
		{
			get
			{
				return this._Geboortedatum;
			}
			set
			{
				if ((this._Geboortedatum != value))
				{
					this.OnGeboortedatumChanging(value);
					this.SendPropertyChanging();
					this._Geboortedatum = value;
					this.SendPropertyChanged("Geboortedatum");
					this.OnGeboortedatumChanged();
				}
			}
		}
		
        [Required]
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geslacht", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Geslacht
		{
			get
			{
				return this._Geslacht;
			}
			set
			{
				if ((this._Geslacht != value))
				{
					this.OnGeslachtChanging(value);
					this.SendPropertyChanging();
					this._Geslacht = value;
					this.SendPropertyChanged("Geslacht");
					this.OnGeslachtChanged();
				}
			}
		}
		
        [Required]
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
        [Required]
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this.OnPostcodeChanging(value);
					this.SendPropertyChanging();
					this._Postcode = value;
					this.SendPropertyChanged("Postcode");
					this.OnPostcodeChanged();
				}
			}
		}
		
        [Required]
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Woonplaats", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Woonplaats
		{
			get
			{
				return this._Woonplaats;
			}
			set
			{
				if ((this._Woonplaats != value))
				{
					this.OnWoonplaatsChanging(value);
					this.SendPropertyChanging();
					this._Woonplaats = value;
					this.SendPropertyChanged("Woonplaats");
					this.OnWoonplaatsChanged();
				}
			}
		}
		
        [Required]
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="Int")]
		public System.Nullable<int> userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					if (this._Gebruiker.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIDChanging(value);
					this.SendPropertyChanging();
					this._userID = value;
					this.SendPropertyChanged("userID");
					this.OnuserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klanten_Boekingen", Storage="_Boekingens", ThisKey="KlantNummer", OtherKey="Boeking_KlantNr")]
		public EntitySet<Boekingen> Boekingens
		{
			get
			{
				return this._Boekingens;
			}
			set
			{
				this._Boekingens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gebruiker_Klanten", Storage="_Gebruiker", ThisKey="userID", OtherKey="userID", IsForeignKey=true)]
		public Gebruiker Gebruiker
		{
			get
			{
				return this._Gebruiker.Entity;
			}
			set
			{
				Gebruiker previousValue = this._Gebruiker.Entity;
				if (((previousValue != value) 
							|| (this._Gebruiker.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Gebruiker.Entity = null;
						previousValue.Klantens.Remove(this);
					}
					this._Gebruiker.Entity = value;
					if ((value != null))
					{
						value.Klantens.Add(this);
						this._userID = value.userID;
					}
					else
					{
						this._userID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Gebruiker");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Boekingens(Boekingen entity)
		{
			this.SendPropertyChanging();
			entity.Klanten = this;
		}
		
		private void detach_Boekingens(Boekingen entity)
		{
			this.SendPropertyChanging();
			entity.Klanten = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gebruikers")]
	public partial class Gebruiker : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _userID;
		
		private string _rol;
		
		private string _Voornaam;
		
		private string _Achternaam;
		
		private string _tussenvoegsel;
		
		private string _wachtwoord;
		
		private EntitySet<Klanten> _Klantens;
		
		private EntityRef<Rollen> _Rollen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIDChanging(int value);
    partial void OnuserIDChanged();
    partial void OnrolChanging(string value);
    partial void OnrolChanged();
    partial void OnVoornaamChanging(string value);
    partial void OnVoornaamChanged();
    partial void OnAchternaamChanging(string value);
    partial void OnAchternaamChanged();
    partial void OntussenvoegselChanging(string value);
    partial void OntussenvoegselChanged();
    partial void OnwachtwoordChanging(string value);
    partial void OnwachtwoordChanged();
    #endregion
		
		public Gebruiker()
		{
			this._Klantens = new EntitySet<Klanten>(new Action<Klanten>(this.attach_Klantens), new Action<Klanten>(this.detach_Klantens));
			this._Rollen = default(EntityRef<Rollen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this.OnuserIDChanging(value);
					this.SendPropertyChanging();
					this._userID = value;
					this.SendPropertyChanged("userID");
					this.OnuserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string rol
		{
			get
			{
				return this._rol;
			}
			set
			{
				if ((this._rol != value))
				{
					if (this._Rollen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnrolChanging(value);
					this.SendPropertyChanging();
					this._rol = value;
					this.SendPropertyChanged("rol");
					this.OnrolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voornaam", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Voornaam
		{
			get
			{
				return this._Voornaam;
			}
			set
			{
				if ((this._Voornaam != value))
				{
					this.OnVoornaamChanging(value);
					this.SendPropertyChanging();
					this._Voornaam = value;
					this.SendPropertyChanged("Voornaam");
					this.OnVoornaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Achternaam", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Achternaam
		{
			get
			{
				return this._Achternaam;
			}
			set
			{
				if ((this._Achternaam != value))
				{
					this.OnAchternaamChanging(value);
					this.SendPropertyChanging();
					this._Achternaam = value;
					this.SendPropertyChanged("Achternaam");
					this.OnAchternaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tussenvoegsel", DbType="NVarChar(10)")]
		public string tussenvoegsel
		{
			get
			{
				return this._tussenvoegsel;
			}
			set
			{
				if ((this._tussenvoegsel != value))
				{
					this.OntussenvoegselChanging(value);
					this.SendPropertyChanging();
					this._tussenvoegsel = value;
					this.SendPropertyChanged("tussenvoegsel");
					this.OntussenvoegselChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wachtwoord", DbType="NVarChar(50)")]
		public string wachtwoord
		{
			get
			{
				return this._wachtwoord;
			}
			set
			{
				if ((this._wachtwoord != value))
				{
					this.OnwachtwoordChanging(value);
					this.SendPropertyChanging();
					this._wachtwoord = value;
					this.SendPropertyChanged("wachtwoord");
					this.OnwachtwoordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gebruiker_Klanten", Storage="_Klantens", ThisKey="userID", OtherKey="userID")]
		public EntitySet<Klanten> Klantens
		{
			get
			{
				return this._Klantens;
			}
			set
			{
				this._Klantens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rollen_Gebruiker", Storage="_Rollen", ThisKey="rol", OtherKey="roleType", IsForeignKey=true)]
		public Rollen Rollen
		{
			get
			{
				return this._Rollen.Entity;
			}
			set
			{
				Rollen previousValue = this._Rollen.Entity;
				if (((previousValue != value) 
							|| (this._Rollen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rollen.Entity = null;
						previousValue.Gebruikers.Remove(this);
					}
					this._Rollen.Entity = value;
					if ((value != null))
					{
						value.Gebruikers.Add(this);
						this._rol = value.roleType;
					}
					else
					{
						this._rol = default(string);
					}
					this.SendPropertyChanged("Rollen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Klantens(Klanten entity)
		{
			this.SendPropertyChanging();
			entity.Gebruiker = this;
		}
		
		private void detach_Klantens(Klanten entity)
		{
			this.SendPropertyChanging();
			entity.Gebruiker = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hotelkamers")]
	public partial class Hotelkamer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KamerNummer;
		
		private int _AantalPersonen;
		
		private decimal _MinimumPrijs;
		
		private System.Nullable<decimal> _ActuelePrijs;
		
		private EntitySet<Boekingen> _Boekingens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKamerNummerChanging(int value);
    partial void OnKamerNummerChanged();
    partial void OnAantalPersonenChanging(int value);
    partial void OnAantalPersonenChanged();
    partial void OnMinimumPrijsChanging(decimal value);
    partial void OnMinimumPrijsChanged();
    partial void OnActuelePrijsChanging(System.Nullable<decimal> value);
    partial void OnActuelePrijsChanged();
    #endregion
		
		public Hotelkamer()
		{
			this._Boekingens = new EntitySet<Boekingen>(new Action<Boekingen>(this.attach_Boekingens), new Action<Boekingen>(this.detach_Boekingens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KamerNummer", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int KamerNummer
		{
			get
			{
				return this._KamerNummer;
			}
			set
			{
				if ((this._KamerNummer != value))
				{
					this.OnKamerNummerChanging(value);
					this.SendPropertyChanging();
					this._KamerNummer = value;
					this.SendPropertyChanged("KamerNummer");
					this.OnKamerNummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AantalPersonen", DbType="Int NOT NULL")]
		public int AantalPersonen
		{
			get
			{
				return this._AantalPersonen;
			}
			set
			{
				if ((this._AantalPersonen != value))
				{
					this.OnAantalPersonenChanging(value);
					this.SendPropertyChanging();
					this._AantalPersonen = value;
					this.SendPropertyChanged("AantalPersonen");
					this.OnAantalPersonenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinimumPrijs", DbType="Decimal(18,0) NOT NULL")]
		public decimal MinimumPrijs
		{
			get
			{
				return this._MinimumPrijs;
			}
			set
			{
				if ((this._MinimumPrijs != value))
				{
					this.OnMinimumPrijsChanging(value);
					this.SendPropertyChanging();
					this._MinimumPrijs = value;
					this.SendPropertyChanged("MinimumPrijs");
					this.OnMinimumPrijsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActuelePrijs", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ActuelePrijs
		{
			get
			{
				return this._ActuelePrijs;
			}
			set
			{
				if ((this._ActuelePrijs != value))
				{
					this.OnActuelePrijsChanging(value);
					this.SendPropertyChanging();
					this._ActuelePrijs = value;
					this.SendPropertyChanged("ActuelePrijs");
					this.OnActuelePrijsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hotelkamer_Boekingen", Storage="_Boekingens", ThisKey="KamerNummer", OtherKey="Boeking_KamerNr")]
		public EntitySet<Boekingen> Boekingens
		{
			get
			{
				return this._Boekingens;
			}
			set
			{
				this._Boekingens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Boekingens(Boekingen entity)
		{
			this.SendPropertyChanging();
			entity.Hotelkamer = this;
		}
		
		private void detach_Boekingens(Boekingen entity)
		{
			this.SendPropertyChanging();
			entity.Hotelkamer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rollen")]
	public partial class Rollen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _roleType;
		
		private EntitySet<Gebruiker> _Gebruikers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnroleTypeChanging(string value);
    partial void OnroleTypeChanged();
    #endregion
		
		public Rollen()
		{
			this._Gebruikers = new EntitySet<Gebruiker>(new Action<Gebruiker>(this.attach_Gebruikers), new Action<Gebruiker>(this.detach_Gebruikers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleType", DbType="NVarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string roleType
		{
			get
			{
				return this._roleType;
			}
			set
			{
				if ((this._roleType != value))
				{
					this.OnroleTypeChanging(value);
					this.SendPropertyChanging();
					this._roleType = value;
					this.SendPropertyChanged("roleType");
					this.OnroleTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rollen_Gebruiker", Storage="_Gebruikers", ThisKey="roleType", OtherKey="rol")]
		public EntitySet<Gebruiker> Gebruikers
		{
			get
			{
				return this._Gebruikers;
			}
			set
			{
				this._Gebruikers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Gebruikers(Gebruiker entity)
		{
			this.SendPropertyChanging();
			entity.Rollen = this;
		}
		
		private void detach_Gebruikers(Gebruiker entity)
		{
			this.SendPropertyChanging();
			entity.Rollen = null;
		}
	}
}
#pragma warning restore 1591
