//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:2.0.50727.6407
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IValutaService")]
public interface IValutaService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/GetValutas", ReplyAction="http://tempuri.org/IValutaService/GetValutasResponse")]
    string[] GetValutas();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/GetConvertedValuta", ReplyAction="http://tempuri.org/IValutaService/GetConvertedValutaResponse")]
    double GetConvertedValuta(int inAmount, string outValuta);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IValutaServiceChannel : IValutaService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ValutaServiceClient : System.ServiceModel.ClientBase<IValutaService>, IValutaService
{
    
    public ValutaServiceClient()
    {
    }
    
    public ValutaServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ValutaServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ValutaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ValutaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string[] GetValutas()
    {
        return base.Channel.GetValutas();
    }
    
    public double GetConvertedValuta(int inAmount, string outValuta)
    {
        return base.Channel.GetConvertedValuta(inAmount, outValuta);
    }
}
