//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotelkamers
    {
        public Hotelkamers()
        {
            this.Boekingen = new HashSet<Boekingen>();
        }
    
        public int KamerNummer { get; set; }
        public int AantalPersonen { get; set; }
        public decimal MinimumPrijs { get; set; }
        public Nullable<decimal> ActuelePrijs { get; set; }
    
        public virtual ICollection<Boekingen> Boekingen { get; set; }
    }
}
