//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klanten
    {
        public Klanten()
        {
            this.Boekingen = new HashSet<Boekingen>();
        }
    
        public int KlantNummer { get; set; }
        public string Voornaam { get; set; }
        public string Achternaam { get; set; }
        public string tussenvoegsel { get; set; }
        public System.DateTime Geboortedatum { get; set; }
        public string Geslacht { get; set; }
        public string Adres { get; set; }
        public string Postcode { get; set; }
        public string Woonplaats { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Boekingen> Boekingen { get; set; }
    }
}
